### ISSUE TITLE
Can you also make this with Feathers SDK?

### ISSUE THREAD

**Issue by leossmith** [PhantomAppDevelopment/city-app#1]
First, i would like to thank you for this. I have been looking for a while for a way to move from Apache Flex to Starling and feathers, but as you know it is of a very different approach. So your app helped a lot. 

If you can also make a version of the app using the Feathers SDK (MXML) this would be awesome.

Thank you,

Leo

**Comment by agentphantom** [comment]
Hi,

Thanks for the comment!

I have plans to port City App to Feathers SDK in the coming weeks. I just need to make sure everything works as I expect.

**Comment by leossmith** [comment]
Great :D thank you for all the work. Having the same app on Flex and Feathers SDK is the perfect guide :)

**Comment by agentphantom** [comment]
Hi,

I just uploaded the Feathers SDK version of this project:

https://github.com/PhantomAppDevelopment/cityapp-feathers-sdk

It requires the latest version of Feathers SDK (3.0 beta as of today).

I made some extra enhancements to the app and modified the theme to be more dynamic.

**Comment by agentphantom** [comment]
Hi again,

I have officially launched the 1.2.0 version of CityApp Feathers SDK edition:
https://github.com/PhantomAppDevelopment/cityapp-feathers-sdk

I also have a little extra:
https://github.com/PhantomAppDevelopment/earthquakeapp-feathers-sdk
